### ISSUE TITLE
Recette pour compiler plink

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/adam-ibs#1]
La recette doit inclure:

- Éditeur C/C++ utilisé (idéalement cross-platform)
- Version de Plink: 1.07 ou 1.90 Beta 3
- Makefile, etc..

**Comment by ikizema** [comment]
For Ubuntu : https://github.com/GELOG/MGL804-PLINK1.9
Tested functioning  versions : 14.04 LTS

**Comment by sfcwallace** [comment]
Il faut ajouter la recette pour mac

**Comment by singemanator** [comment]
Pour Mac: https://github.com/GELOG/MGL804-PLINK1.9-Mac
Version testé avec Yosemite et IDE utilisé CLion

**Comment by davidonlaptop** [comment]
@singemanator : Super! I've downgraded CMake version requirement from 3.2 to 3.1. If it break things for you, just set it back to 3.2.
