### ISSUE TITLE
Use a dependency manager to build the project

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/adam-ibs#24]
## Description
All the dependencies used in this project (e.g. ADAM's formats, CLI parser, etc.) should be loaded externally via a build tool / dependency manager like Maven or SBT.

## Implementation
Update the README file at the root of the repo to describe how to build the project.

**Comment by ikizema** [comment]
Initialization of scala project is done with Maven :
https://github.com/GELOG/adam-ibs

On each new requirement of dependencies, the pom file will be updated.
