### ISSUE TITLE
Calculate the pairwise IBD/IBS metrics - Part I (--genome)

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/adam-ibs#3]
# Description
Similar to `plink --genome` option. See the [wiki on IBS-MDS Process](https://github.com/GELOG/adam-ibs/wiki/Plink-IBS-MDS-Feature) and the diagram for the Genome file.

The input files are those created in #2.

The fields required for --cluster and --mds-plot are:
- FID1: family ID of individual 1
- IID1: individual ID of individual 1
- FID2: family ID of individual 2
- IID2: individual ID of individual 2
- DST: IBS distance
- PPC: IBS binomial test

There is more fields, but they are will be done in Part II.

# Analysis
Add a comment to this issue with:
- plink version used as reference (1.07 or 1.90 beta 3)
- relevant C++ function name(s) and the file name(s) where they appear
- Document the algorithm and/or mathematical formula to compute the fields:
  - DST
  - PPC
  - any other field required as a dependency

# Design
Add a comment to this issue describing how this will be implemented in Spark, and how it differs from plink.

Also update the class diagram on the [wiki page describing PLink formats](https://github.com/GELOG/adam-ibs/wiki/Plink-File-Formats) (when incomplete) and add a class diagram describing the models implemented in Scala for this feature on the [wiki page on the MGL804 formats](https://github.com/GELOG/adam-ibs/wiki/MGL804-File-Formats).

# Implementation
The implementation should use:
- Scala
- Spark RDD
- Spark MLlib / GraphX (if appropriate)

**Important note:** The model can be only in memory for now, but you'll need to integrate into the [ADAM format](https://github.com/GELOG/adam-ibs/wiki/ADAM_Format) later on. You'll probably need to create a new record type.

**Comment by ikizema** [comment]
**Informations pouvant être utiles **

**Visualisation de contenu dans le fichier .bed  :**
$ xxd -b test.bed

**Comment by ikizema** [comment]
Bonjour, pourriez-vous faire un  statut sur ce point ?

**Comment by sfcwallace** [comment]
Voici le lien vers la page du Wiki décrivant les champs du fichier .genome: https://github.com/GELOG/adam-ibs/wiki/Algorithm-for-Pairwise--IBS-IBD-computation-(--genome)
