### ISSUE TITLE
IBS Clustering outliers format

### ISSUE THREAD

**Issue by ikizema** [GELOG/adam-ibs#31]
Compléter [Wiki](https://github.com/GELOG/adam-ibs/wiki/Plink-File-Formats) avec le format de données IBS Clustering outliers format (partie 6).

Rq: merci de mettre le lien vers la documentation officielle.

**Comment by karim73** [comment]
- Commande pour plink 1.07 : plink `--file` data `--cluster` `--neighbour` `n1` `n2`
- Commande pour plink 1.9  : plink `--neighbour` `n1` `n2` \(Pas besoin de specifier --cluster\) 

Où : `n1` et `n2` représentent l'offset des voisins les plus proches.

La commande genere un fichier de la structure suivante. 
![IBS Outliers  Class Diagram](http://yuml.me/diagram/plain;dir:LR/class/[NEAREST|FID: Family ID;IID:            Individual ID;NN: Nearest neighbour level;MIN_DST: IBS distance of nth nearest neighbour;Z: MIN_DST converted to a Z score;FID2: Family ID of the nth nearest neighbour;IID2: Individual ID of the nth nearest neighbour;PROP_DIFF: Proportion of significantly different others])
