### ISSUE TITLE
List of available CLI parsers librairies

### ISSUE THREAD

**Issue by singemanator** [GELOG/adam-ibs#35]
- Make a list of existing CLI parsers librairies available for Java and Scala.
- Describe the PROs and CONs of each.

**Comment by francois-boyer** [comment]
Je crois que cette tâche devrait être supprimée.  Elle est incluse dans la tâche #23

**Comment by singemanator** [comment]
La tâche #23 rassemblée 3 tâches. Je l'ai divisé en sous-tâche
