### ISSUE TITLE
Describe "tree" structure for CLI option

### ISSUE THREAD

**Issue by singemanator** [GELOG/adam-ibs#37]
Describe the "tree" of available commands for the scope of the features implemented in MGL804.

**Comment by francois-boyer** [comment]
Serais-ce possible de définir l'arbre des commandes disponibles et leurs options.  Je pourrai ensuite démarrer la tâche #38.

**Comment by ikizema** [comment]
Voir #36 pour commencer.
PS : Pourquoi il y a deux taches similaires ?
