### ISSUE TITLE
Implement the parser for the CLI option

### ISSUE THREAD

**Issue by singemanator** [GELOG/adam-ibs#38]
Describe the general idea of the solution

**Comment by francois-boyer** [comment]
J'ai besoin que la tâche #37 soit complétée avant de pouvoir démarrer celle-ci.

**Comment by ikizema** [comment]
Voir #36.
La tache #37 est dans "Donne" en tant que duplicata en attendant sa suppression par le créateur.

**Comment by singemanator** [comment]
@ikizema le code du parser est sur github:  https://github.com/GELOG/adam-ibs/tree/CLI-parser/src

**Comment by ikizema** [comment]
Comme discuté précédemment, on utilise Maven pour la gestion des dépendances. Utilisation d'un autre gestionnaire n'est donc pas possible. Pour compléter la tache, il faut migrer sur Maven et intégrer au projet.

**Comment by karim73** [comment]
J'ai installé scalop via maven avec la dependance suivante. cc @singemanator 
<dependency>
<groupId>com.loopfor.scalop</groupId>
<artifactId>scalop_2.10</artifactId>
<version>1.1</version>
</dependency>

**Comment by ikizema** [comment]
@karim73, cool !
Tu a ajouté les dépendances, migré sur Maven le parcer crée par @singemanator et validé son fonctionnement ? Si c'est le cas, pourrai-tu faire un commit de la branche pour que l'on merge avec master ?

**Comment by karim73** [comment]
J'ai créé une nouvelle branche "karim". en fait il s'agit d'un "merge" manuel entre la branche master et la branche CLI-pasrser. J'y ai ajouté les dependances scallop, logback. Le tout compile, sauf le parser qui fonctionne pas. J'ai refactoré la class Main pour les besoins du test. J'avais pingé @singemanator concernant le fonctionnement de son CLI, mais pas eu de reponse encore

**Comment by karim73** [comment]
PS : le gitignore doit etre modifié pour ignorer le dossier .idea d'etre pushé

**Comment by singemanator** [comment]
@ikizema @karim73, je vais revoir le code du CLI pour le faire fonctionner avec l'ensemble du projet au plus tard lundi

**Comment by karim73** [comment]
@singemanator , dans ce cas, tu peux laisser cette tache pour moi.
Je propose que je m'occupe du parser et du logger.

**Comment by singemanator** [comment]
@karim73, pas de problème. Tu as juste à reprendre le code que j'avais fais et l'intégrer. Je l'avais testé et démontré en classe. Il fonctionne. Si tu as des problèmes pour le comprendre envoies moi un message.

**Comment by karim73** [comment]
Le CLI est fonctionnel maintenant avec scallop

**Comment by ikizema** [comment]
Bonjour, j'ai mergé CLI avec le projet global. A première vue, je constate une limitation de l'outil. 

Je souhaite exécuter la ligne suivante : adam-ibs --file ./DATA/test --make-bed (exécuter adam-ibs en sur le ficher ./DATA/test et appliquer le traitement make-bed). Le parceur CLI exécute uniquement la première option (--file) sans exécuter --make-bed. 

**Questions :** Est-il possible de prendre en compte l'ensemble des options ? Comment le faire ? Est-il possible de faire les modifications nécessaires pour permettre un tel fonctionnement ?

Merci,
Ivan

**Comment by ikizema** [comment]
Rebonjour, 

Finalement j'ai trouvé comment faire les modifications nécessaires. Il manquait la vérification des l'ensemble des options. Désormais il est possible de faire quelque chose comme : adam-ibs --file ./DATA/test --make-bed .

Tout fonctionne, je ferme le point.
