### ISSUE TITLE
Logging processing

### ISSUE THREAD

**Issue by ikizema** [GELOG/adam-ibs#39]
On the same way as plink does, we need to log the program execution.
 - 1. Find an easy way to log the program execution.
 - 2. Implement it.

I have created a WriteLog scala class which I call any time I would like to write a log.  For now, it does only "println".  A logging to file functionality needs to be implemented.

**Comment by ikizema** [comment]
Implement a SLF4J solution.

**Comment by davidonlaptop** [comment]
FYI. It seems that logback <http://logback.qos.ch/> is now the successor of
SLF4J, having a common API with SLF4J.

**Comment by francois-boyer** [comment]
@karim73, I did most of the persistance job for the moment.  I still need to document how it works in order to explain it to the team, but that said, I think you can start working on another task. This could be useful to other member of the team. 

You can take care of it?  If yes, please assigne the task to yourself and move this task to "in progress".

Thanks,

**Comment by karim73** [comment]
Ok, je vais consulter la librairie suggérée plus haut.
@ikizem, dans ce cas je vais laisser tomber apache.parquet et je vais m'occuper de la tâche #39

**Comment by ikizema** [comment]
Ok @karim73, c'est très bien.

**Comment by ikizema** [comment]
Pour repondre à @karim73 "j'aurais besoin d'aide pour gerer les dependanses avec maven pour inclure au projet cette librairie" :

Très bien @karim73. Avant de passer à l'implementation,  peux tu apporter plus de precisions :
- Quel outil a été choisi ?
- Pourquoi ?
- S'il s'agit de logback, est-il utilisable sur scala ? A-tu trouvé des projets qui l'implementent ? (PS: dans le choix il faut prendre en compte la simplicité d'accès aux informations et aux exemples).

Une fois defini, en mettant ici la librerie exacte (avec version) que tu souhaite utiliser, je l'importerai dans projet si tu veux.
Merci,

**Comment by karim73** [comment]
@ikizema ,
L'outil que "j'ai choisi", est la librairie est : scala-logging, car il s'agit d'une librairie de logging en scala basée sur SL4J.
Une fois les dependenses reglés, son utilisation est dès plus simples :
Exemple :
val logger = Logger(LoggerFactory.getLogger("name"))
logger.debug("This is very convenient ;-)")

Il s'agit d'un wrapper de SLF4J

Si vous connaissez d'autre librairie, je suis dispo pour les etudier

**Comment by ikizema** [comment]
Ok @karim73, ce projet me plaisait bien aussi.

Il est sur Maven Central, pour l'integrer au projet il faut l'inclure dans pom.xml :
    Group id / organization: com.typesafe.scala-logging
    Artifact id / name: scala-logging
    Latest version is 3.1.0

Tiens nous au courant,

**Comment by karim73** [comment]
Merci pour l'astuce.

**Comment by karim73** [comment]
@ikizema , voici ce que ça donne.
on verra ça plus tard si tu veux.

Dans pom.xml j'ai ajouté ce block :
    
    <dependency>
      <groupId>com.typesafe.scalalogging</groupId>
      <artifactId>scala-logging</artifactId>
      <version>3.1.0</version>
    </dependency>
kimou@127-[16:50:48] >  mvn install:install-file -Dfile=/home/karim/Documents/docs/MGL804/master/adam-ibs/ -DpomFile=/home/karim/Documents/docs/MGL804/master/adam-ibs/pom.xml
[INFO] Scanning for projects...
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.3/maven-clean-plugin-2.3.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.3/maven-clean-plugin-2.3.pom (5 KB at 28.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/12/maven-plugins-12.pom (12 KB at 117.1 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/9/maven-parent-9.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/9/maven-parent-9.pom (33 KB at 254.5 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.3/maven-clean-plugin-2.3.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.3/maven-clean-plugin-2.3.jar (17 KB at 116.8 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.3/maven-install-plugin-2.3.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.3/maven-install-plugin-2.3.pom (5 KB at 51.6 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/13/maven-plugins-13.pom
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/13/maven-plugins-13.pom (12 KB at 121.1 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.3/maven-install-plugin-2.3.jar
Downloaded: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-install-plugin/2.3/maven-install-plugin-2.3.jar (23 KB at 151.0 KB/sec)
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building adam-ibs 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-install-plugin:2.3:install-file (default-cli) @ adam-ibs ---
[INFO] Installing /home/karim/Documents/docs/MGL804/master/adam-ibs to /home/karim/.m2/repository/com/ets/mgl804/adam-ibs/0.1.0/adam-ibs-0.1.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.673s
[INFO] Finished at: Wed Jun 17 16:51:09 EDT 2015
[INFO] Final Memory: 7M/226M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.3:install-file (default-cli) on project adam-ibs: Error installing artifact 'com.ets.mgl804:adam-ibs:jar': Failed to install artifact com.ets.mgl804:adam-ibs:jar:0.1.0: /home/karim/Documents/docs/MGL804/master/adam-ibs (est un dossier) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by karim73** [comment]
Utilisation de logback pour le logging.
Packages a inclure : logback-core et logback-classis. Il existe un troiseme package : logback-access qui s'integre avec les servlets (je l'ai pas retenu  pour le projet)
le package slf4j est inclus dans logback-core.

Configuration speciale a faire :

Dans pom.xml :  exclure le package slf4j dans la declaration du package spark ( dù à un conflit de StaticLoggerBinder (slf4j de spark vs logback )
Ajout d'un fichier de config : src/main/resources/logback.xml
- declaration des appenders : ici seule la console est utilisée, 
- J'ai desactivé tous les logs (specialement les logs generés par spark )
- j'ai activé seulement les logs du package com.ets..mgl804, avec le niveau le plus bas : TRACE.
logger name="com.ets.mgl804" level="TRACE" /

Utilisation :
dans chaque class où on souhaite loguer : 
- import le package  : import org.slf4j.{LoggerFactory, Logger}
- declarer une instance du logger :
def logb = LoggerFactory.getLogger(this.getClass())
(le parametre this.getClass() peut etre remplacé par un autre nom )
- loguer : 
logb.info("hellow worl ")
Les differetns level sont (dans l'ordre ) : trace, debug, info, warn, error
-  Pour diminiuer la verbositié, on a juste a modifier le level dans logback.xml.
Exemple, si le level par defaut est setté a WARN, alors tous les logs de type : info, trace, debug ne seront pas affiché. 
C'est au developpeur de choisir (selon contexte) quelle methode(level) a utiliser  ( log.info() ou log.debug() ect ..)

- logback a introduit un optimisateur :
on peut loguer une expression avec parametre de deux manieres :
log.info("hello "+ str )
ou
log.info("hello {}" , str )
Dans le premier cas, l'expression sera systematiquement evaluée
Dans le deuxieme cas, l'expression ne sera evalué que si le level est superieur au level par defaut ( log.info("helllo {}" , str ) ne sera pas evalué si le level par defaut est WARN ).
