### ISSUE TITLE
Mapping des données .ped, .map, .bin, .fam, .bed

### ISSUE THREAD

**Issue by ikizema** [GELOG/adam-ibs#43]
L'objectif de cette tache est de proposer un mapping de format de données Plink dans le [Format ADAM](https://github.com/GELOG/adam-ibs/wiki/ADAM_Format). 

Proposition de mapping pour le extensins .ped, .map, .bim, .fam, .bed.

**Comment by ikizema** [comment]
Voici la première proposition de mapping dans le format de ADAM :
![image](https://raw.githubusercontent.com/GELOG/adam-ibs/master/WIKI/img/Plink_to_ADAM%20Format_Mapping.jpeg)

@davidonlaptop, quel est ton avis sur le diagramme ? Pourrai-tu valider/rectifier avant le début d’implémentation ?

**Comment by ikizema** [comment]
Suite aux premiers retours, voici la deuxime version :

![image](https://raw.githubusercontent.com/GELOG/adam-ibs/master/WIKI/img/Plink_to_ADAM_Format_Mapping_v2.jpeg)

Le GenotypeAllele de Adam et un enum et non une classe, l'équivalent de GenotypeCode ne semble pas present. Peu d'élements se mappent dans le format ADAM, je propose de simplifier l'ensemble en créant une classe Nucleotide.

@davidonlaptop, pouvons nous commencer l'implementation ?

**Comment by singemanator** [comment]
Voici la 3ème version avec le genome: 

![image](https://raw.githubusercontent.com/GELOG/adam-ibs/master/WIKI/img/Plink%20Mapping%20to%20ADAM%20Format%20v3%20-%20Plink%20format%20mappong%20to%20ADAM%20Format.png)

Il n'y aucune correspondance avec le format ADAM. Ce que je propose c'est d'ajouter une classe "Genome" qui contiendra l'ensemble des attributs définies dans le fichier "Genome record".

@davidonlaptop, nous avons besoin d'un feedback. Merci

**Comment by davidonlaptop** [comment]
For the genome record in ADAM, we should probably nest the Individual record inside: (see image below):

http://yuml.me/diagram/scruffy/class/[Genome%7C-individual1%20:%20Individual;-individual2%20:%20Individual;-RT;-EZ;-etc]

**Comment by davidonlaptop** [comment]
For the gender, please use an Enum and not an integer.

**Comment by davidonlaptop** [comment]
For the Genotype, the relationships does not seem optimal... but I'd have to look at it more in details after my vacation.

As long as it your algorithm produces similar results, you can start coding it.

**Comment by singemanator** [comment]
@ikizema, hier je t'ai envoyé le lien de la nouvelle version sur LucidChart sur format de donnée. Si tu ne l'as pas reçu envoies moi un courriel.

**Comment by ikizema** [comment]
@singemanator, si tu publie ton model dans cette tache, ça serait plus simple pour le suivi...

**Comment by ikizema** [comment]
Modification apportées: 
- Modification du type "nucleotideAllele*" par un Enum
- Reorganisation en composantes

![image](https://raw.githubusercontent.com/GELOG/adam-ibs/master/WIKI/img/Plink_to_ADAM_Format_Mapping_v5.jpeg)

**Comment by ikizema** [comment]
Bonjour @davidonlaptop, as-tu eu le temps de regarder la derniere proposition du modele des donnes ?

**Comment by ikizema** [comment]
Comme convenu hier, les modifications au niveau de Genotype :

![image](https://raw.githubusercontent.com/GELOG/adam-ibs/master/WIKI/img/Plink_to_ADAM_Format_Mapping_v6.jpeg)

**Comment by Aboubakary** [comment]
Salut, je croyais que les Z0, Z1, Z2, IBS0, IBS1, IBS2 devaient venir dans le genome, qui aussi devait changer de nom!

**Comment by singemanator** [comment]
Oui tu as raison @Aboubakary, je suis justement en train de faire les modifications par rapport au génome.

**Comment by singemanator** [comment]
Voici les modifications pour le fichier .genome

![image](https://raw.githubusercontent.com/GELOG/adam-ibs/master/WIKI/img/Plink_to_ADAM_Format_Mapping_v7.png)

**Comment by ikizema** [comment]
Bonjour @singemanator. Desolé de t'embeter, mais il y a un leger probleme au niveau des noms. Autre le coté metier (ce n'est pas moi qui se potitionne la dessus), c'est la partie technique qui me gene.  L'utilisation des " " et "/" n'est pas possible dans le nommage des classses et des attributs. Aussi, il est preferable d'eviter des nos à ralonge (les derniers attributs).

Ce n'est pas un exercice evident de trouver une terminogie parlante et simple dans le domaine de la genetique lorsque nous faisons du logiciel... Comme évoqué hier, ce n'est pas trop de nottre ressors de trouver un nommage metier le plus  pertinent possible... Par contre, on se doit de respect les contraintes techniques.

**Comment by singemanator** [comment]
Salut @ikizema, parfait j'en prend, je vais y apporter les modifications nécessaires.

**Comment by ikizema** [comment]
Salut @singemanator , tu souhaite le faire pour quand ? Pour rappel, on s'était éngagé le terminer pour jeudi afin que David puisse le valider...

**Comment by singemanator** [comment]
Voici les modifications pour le fichier .genome sans les ("/") c'était une erreur d'inattention.

![image](https://raw.githubusercontent.com/GELOG/adam-ibs/master/WIKI/img/Plink_to_ADAM_Format_Mapping_v8.jpeg)


Mais deux questions: 
1) Lors de la dernière réunion, j'ai cru comprendre que @davidonlaptop avait dit qu'il ne fallait pas hésiter à mettre de long nom comme ceux qui existe dans un autre schéma. Donc, est-ce que j'ai mal compris?
2) Lorsqu'on fait: Enum("UN", "OT") etc. cela signifie que le Enum est de type String.

**Comment by singemanator** [comment]
J'ai modifié certains noms encore
![image](https://raw.githubusercontent.com/GELOG/adam-ibs/master/WIKI/img/Plink_to_ADAM_Format_Mapping_v9.jpeg)

**Comment by davidonlaptop** [comment]
Bonjour @singemanator @ikizema,

Le schéma est beaucoup mieux comme ça!

Quelques suggestions mineures (si vous avez le temps):

Dans Pairwise IBS IBD:

   - Renommer indi1/2 a individual1/2
   - relationType: il faut trouver un nom pour l'Enum (que dites-vous de
   IBS_IBD_RelationType?). Aussi, est-ce possible d'éclaircir les valeurs UN,
   FS, HS, PO, OT... Qu'est-ce quelles veulent dires?

Dans Individual:

   - Fusionner Phenotype avec Individual (relation 1:1). On pourrait
   l'appeler mainPhenotype : String.

Bon travail les gars!

**Comment by ikizema** [comment]
Salut @davidonlaptop, je vais répondre pour ce qui me concerne. En ce qui concerne le phénotype, cela déjà été le cas la semaine dernière et résultait d,un choix réfléchi. Il est vrai que dans les donnes que nous avons, le phenotype possède seulement un string. Cependant, je pense que le besoin peut grandir rapidement, on pourrait imaginer plusieurs paramètres phénotypiques dans la classe... J'ai donc crée une classe a part pour pouvoir compléter les informations au besoin par la suite. Je laisse ainsi ou je l’inclus dans l'attribut d'individu ?

**Comment by davidonlaptop** [comment]
+Beatriz

Je t'accorde qu'un phénotype est bien un concept en soi; mais je ne crois
pas qu'il y'a des informations supplémentaires qu'on veuille stocker pour
un phénotype. Cela doit rester très flexible car la nomenclature des
symptômes (e.g. fièvre, etc.) et ca serait beaucoup de travail de faire un
modèle générique pour tous les phénotypes existants. En plus la médecine
occidentale est très différente de la médecine indienne ou chinoise.

Selon ce que je comprends, plink permet de mettre un phenotype principal
par individu, ou sinon de spécifier une liste de phénotypes alternatifs
dans un fichier a part. Dans cette optique, je verrais un attribut
"mainPhenotype : String", et un attribut "secondaryPhenotypes :
List<String>" lorsqu'on sera rendu la.


2015-07-14 14:55 GMT-04:00 ikizema <notifications@github.com>:

**Comment by davidonlaptop** [comment]
En effet ce serait beaucoup de travail de faire un modèle générique pour tous les phénotypes existants  ou a venir. 
En plus la médecine occidentale est très différente de la médecine indienne ou chinoise.--> Je ne comprends pas le rapport de cette phrase. Qui a parle de medecine chinois ou indienne???
 Cependant ceci semble est une solution viable: plusieurs paramètres phénotypiques dans la classe--> qui permettrait de creer les phnotypes et les parametres associes a ce phenotypes, cela donnerait plus de liberte a la personne qui cree ses phenotypes. Donc on aurait la flexibilite pour inclure les phenotypes existants et a venir.Beatriz Sonja Kanzki
Bsc BioinformaticsDr Pavel Hamet's LabDr Alain April's team
      De : David Lauzon <davidonlaptop@gmail.com>
 À : GELOG/adam-ibs <reply@reply.github.com> 
Cc : GELOG/adam-ibs <adam-ibs@noreply.github.com>; Beatriz Kanzki <beatriz_kanzki@yahoo.ca> 
 Envoyé le : mardi 14 juillet 2015 15h56
 Objet : Re: [adam-ibs] Mapping des données .ped, .map, .bin, .fam, .bed (#43)
   
+Beatriz
Je t'accorde qu'un phénotype est bien un concept en soi; mais je ne crois pas qu'il y'a des informations supplémentaires qu'on veuille stocker pour un phénotype. Cela doit rester très flexible car la nomenclature des symptômes (e.g. fièvre, etc.) et ca serait beaucoup de travail de faire un modèle générique pour tous les phénotypes existants. En plus la médecine occidentale est très différente de la médecine indienne ou chinoise.
Selon ce que je comprends, plink permet de mettre un phenotype principal par individu, ou sinon de spécifier une liste de phénotypes alternatifs dans un fichier a part. Dans cette optique, je verrais un attribut "mainPhenotype : String", et un attribut "secondaryPhenotypes : List<String>" lorsqu'on sera rendu la.

2015-07-14 14:55 GMT-04:00 ikizema <notifications@github.com>:

Salut @davidonlaptop, je vais répondre pour ce qui me concerne. En ce qui concerne le phénotype, cela déjà été le cas la semaine dernière et résultait d,un choix réfléchi. Il est vrai que dans les donnes que nous avons, le phenotype possède seulement un string. Cependant, je pense que le besoin peut grandir rapidement, on pourrait imaginer plusieurs paramètres phénotypiques dans la classe... J'ai donc crée une classe a part pour pouvoir compléter les informations au besoin par la suite. Je laisse ainsi ou je l’inclus dans l'attribut d'individu ?—
