### ISSUE TITLE
scala-Logging 

### ISSUE THREAD

**Issue by karim73** [GELOG/adam-ibs#44]
j'aurais besoin d'aide pour gerer les dependanses avec maven pour inclure au projet cette librairie

**Comment by ikizema** [comment]
Je propose de se referer à la tache #39 pour ce point, qui est la tache originale et identique. Pourquoi generer les points 100% redondants ? Je te propose de la fermer et continuer la discussion dans #39.

**Comment by ikizema** [comment]
@karim73, quel est ton avis, tu t-en occupe de la fermeture ?

**Comment by karim73** [comment]
Un instant Mr Ivan
J'ai juste soumis un problème dans l'outil de suivi de 'bug'.
Je viens juste de me rendre compte qu'il est mappé sur waffle.io
Je le supprime !.
Merci !

**Comment by ikizema** [comment]
Oui, ca arrive Mr Karim.  Tu saus s'il y a moyen de le supprimer completement car ca complexifie enormement la lecture. Au bour d'u moment on va se perdre dans les taches vides.
