### ISSUE TITLE
Parametrage environnement de developpement.

### ISSUE THREAD

**Issue by ikizema** [GELOG/adam-ibs#45]
La nouvelle tache pour suivre l'évolution de paramétrage d'environnement de développement.

**Comment by ikizema** [comment]
@singemanator, @sfcwallace, j'ai crée la tache pour échanger sur votre paramétrage de l'environnement de développement. On a validation de fonctionnement de dépôt. Le point est pressent depuis plus de deux semaines et devient sérieusement bloquant. Pouvez-vous attribuer cette tache et nous tenir informé sur l'évolution ?

**Comment by ikizema** [comment]
Salut, vous arrivez à exécuter le code ?

**Comment by singemanator** [comment]
Salut, on n'a pas encore eu le temps de le faire, mais on le fera avant la fin de cette semaine

**Comment by ikizema** [comment]
Salut, comme tu le sens. Dans notre cas ce sont plus les mercredi qui terminent les semaines et non les dimanches. En soi, cette realisation n'est pas indispensable au projet. Par contre, si je le comprends bien, dans votre cas c'est une contrainte pour avancer sur #32 et #38. En attendant,  Karim semble avoir repris #38 et l'adapté aux contraintes du projet. Quelle serait alors la date pour la réalisation de #32 ?

**Comment by karim73** [comment]
elle consiste en quoi cette tâche ? j'ai pas trop compris

**Comment by ikizema** [comment]
Oui, cette tache concerne uniquement @singemanator, @sfcwallace. Cela fait plusieurs semaines qu'ils n'arrivent pas à executer le code de projet. C'est un moyen de leur fournir les informations necessaires....

**Comment by karim73** [comment]
D'accord. Mais je voulais savoir, si le but de cette tâche est de fournir une recette pour executer le code scala ( la branche master par exemple ) sur un Mac ?

**Comment by ikizema** [comment]
Je ne sais pas, on a deja produit des guides. T'arrive à l'executer sans problemes sur Linux et sur Mac... Je pense que c'est vraiment eux qui doivent être moteurs sur ce point et nous poser des question concretes pour avancer. On est plus la pour repondre aux questions.

**Comment by karim73** [comment]
J'ai reussi a compilé, executé le code ( branche master et la branche Karim ) sur Ubuntu12.04 et Mac Yosemite.

**Comment by singemanator** [comment]
Bonjour, on a réussi à compiler le projet. Le problème était vraiment la version de Java utilisé. La version 1.8 ne fonctionne pas pour compiler le projet mais la version 1.7 fonctionne. Désolée du retard tout le monde. Pour la rencontre mercredi, on va rajouter le code du genome dans le projet principal.
