### ISSUE TITLE
Cleanup the repo used during MGL804's summer

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/adam-ibs#48]
For each of the repo below:
- https://github.com/GELOG/example-avro-parquet-spark
- https://github.com/GELOG/MGL804-PLINK1.9-Mac
- https://github.com/GELOG/MGL804-PLINK1.9
- https://github.com/GELOG/plink
- https://github.com/GELOG/plink-ng

Comment:
- if they are still useful for the evolution of the ADAM-IBS project.
- if they can be opensourced (non-private)

**Comment by ikizema** [comment]
https://github.com/GELOG/example-avro-parquet-spark -> il s'agit de tutoriel pour l'utilisation de avro/parquet. Je ne l'utilise pas. Je l'ai mis en open, peut être supprimé...
    https://github.com/GELOG/MGL804-PLINK1.9-Mac -> supprimé
    https://github.com/GELOG/MGL804-PLINK1.9 -> supprimé
    https://github.com/GELOG/plink -> je ne l'utilise pas, je crois que c'est toi qui l'avait crée
    https://github.com/GELOG/plink-ng -> je ne l'utilise pas

**Comment by davidonlaptop** [comment]
super! merci Ivan
