### ISSUE TITLE
Use a single command to build adam-ibs

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/adam-ibs#51]
It should be possible to build the project with a single command, e.g. not have to change folder or other manual operations.

**Comment by ikizema** [comment]
La première option décrite dans wiki build n'est pas suffisamment "sinle" ?

**Comment by davidonlaptop** [comment]
Je n'ai pas vu de wiki build ??

Mais j'ai reussi a faire fonctionner avec mvn clean package sur linux (single step).
